# This workflow will detect pushes to the main branch, and build qmd files to HTML
# The built HTML files are published to the gh-pages branch
# The gh-pages branch can then be published to GitHub Pages by a different action

# This action is based on https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml

on:
  push:
    branches: main
  workflow_dispatch:

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE

      # From https://github.com/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
